
FROM ubuntu:24.04
LABEL maintainer="AzureDevSecops"
LABEL environment="Production"

# Install nginx
RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

# Create /var/lib/nginx/body and set ownership to www-data
RUN mkdir -p /var/lib/nginx/body && chown -R www-data:www-data /var/lib/nginx

# Create document root and add a simple index.html file
RUN mkdir -p /var/www/html && \
    echo "<h1>Hello from Nginx container!</h1>" > /var/www/html/index.html && \
    chown -R www-data:www-data /var/www/html

# Replace default nginx.conf with custom config
COPY src/nginx.conf /etc/nginx/nginx.conf

# Use www-data user to run the container
USER www-data

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
